{application,sharp_pusher,
             [{description,[]},
              {vsn,"1"},
              {registered,[]},
              {applications,[kernel,stdlib]},
              {mod,{sharp_pusher_app,[]}},
              {env,[]},
              {modules,[apns_sup,http_handler,mqtt_sup,sharp_pusher,
                        sharp_pusher_app,sharp_pusher_sup]}]}.
